In [4]:
import pandas as pd
string_data = pd.Series(['aardark','artichoke',np.nan,'avocado'])

In [5]:
string_data

0      aardark
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data[0] = None

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [9]:
from numpy  import nan as NA

In [10]:
data = pd.Series([1,NA,3.5,NA,7])

In [11]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])

In [15]:
cleaned = data.dropna()

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
cleaned 

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = NA

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis=1,how ='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.randn(7,3))

In [23]:
df.iloc[:4,1] = NA

In [24]:
df.iloc[:2,2] = NA

In [25]:
df

0         1         2
0  0.246297       NaN       NaN
1 -1.013501       NaN       NaN
2 -0.658923       NaN  0.198294
3  1.325003       NaN  0.848208
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [27]:
df.dropna()

0         1         2
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [28]:
df.dropna(thresh=2)

0         1         2
2 -0.658923       NaN  0.198294
3  1.325003       NaN  0.848208
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [29]:
df.fillna(0)

0         1         2
0  0.246297  0.000000  0.000000
1 -1.013501  0.000000  0.000000
2 -0.658923  0.000000  0.198294
3  1.325003  0.000000  0.848208
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [31]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.246297  0.500000  0.000000
1 -1.013501  0.500000  0.000000
2 -0.658923  0.500000  0.198294
3  1.325003  0.500000  0.848208
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [32]:
_ = df.fillna(0,inplace=True)

In [33]:
df

0         1         2
0  0.246297  0.000000  0.000000
1 -1.013501  0.000000  0.000000
2 -0.658923  0.000000  0.198294
3  1.325003  0.000000  0.848208
4 -0.780233  1.732733 -1.202847
5 -0.202974  0.008201 -0.253575
6 -0.236929  1.433738 -1.038208

In [34]:
df = pd.DataFrame(np.random.randn(6,3))

In [35]:
df.iloc[2:,1] = NA

In [36]:
df.iloc[4:,2] = NA

In [37]:
df

0         1         2
0  1.795563 -0.863434 -1.107204
1  0.800239  0.442623 -2.093339
2  0.089918       NaN -0.527132
3 -0.522780       NaN -0.396843
4  1.696168       NaN       NaN
5 -1.088566       NaN       NaN

In [39]:
df.fillna(method = 'ffill')

0         1         2
0  1.795563 -0.863434 -1.107204
1  0.800239  0.442623 -2.093339
2  0.089918  0.442623 -0.527132
3 -0.522780  0.442623 -0.396843
4  1.696168  0.442623 -0.396843
5 -1.088566  0.442623 -0.396843

In [40]:
df.fillna(method = 'ffill',limit=2)

0         1         2
0  1.795563 -0.863434 -1.107204
1  0.800239  0.442623 -2.093339
2  0.089918  0.442623 -0.527132
3 -0.522780  0.442623 -0.396843
4  1.696168       NaN -0.396843
5 -1.088566       NaN -0.396843

In [41]:
data = pd.Series([1,NA,3.5,NA,7])

In [42]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [46]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],
                     'k2': [1,1,2,3,3,4,4]})

In [47]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [48]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [49]:
data['v1'] = range(7)

In [52]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [80]:
data = pd.DataFrame({'food':['bacon','pulled pork','Bacon','Pastrami','corned beef','bacon','pastrami','honey ham','nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [81]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        Bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [82]:
meat_to_animal = {'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

In [83]:
lowercased = data['food'].str.lower()

In [85]:
data['animal'] = lowercased.map(meat_to_animal)

In [86]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        Bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [87]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [88]:
data = pd.Series([1,-999,2,-999,-1000,3])

In [89]:
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [90]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [91]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [92]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [93]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index = ['Ohio','Colorada','New York'],
                   columns = ['one','two','three','four'])

In [94]:
transform = lambda x :x[:4].upper()

In [95]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [96]:
data.index = data.index.map(transform)

In [97]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [98]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [99]:
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [101]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [102]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [103]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [104]:
bins = [18,25,35,60,100]

In [105]:
cats = pd.cut(ages,bins)

In [106]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [107]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [108]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [110]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [111]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [112]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [113]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [114]:
data = np.random.rand(20)

In [115]:
pd.cut(data,4,precision=2)

[(0.74, 0.94], (0.74, 0.94], (0.13, 0.33], (0.54, 0.74], (0.13, 0.33], ..., (0.33, 0.54], (0.54, 0.74], (0.33, 0.54], (0.54, 0.74], (0.54, 0.74]]
Length: 20
Categories (4, interval[float64]): [(0.13, 0.33] < (0.33, 0.54] < (0.54, 0.74] < (0.74, 0.94]]

In [116]:
data = np.random.randn(1000)

In [117]:
cats = pd.qcut(data,4)

In [118]:
cats

[(-3.566, -0.634], (-0.00534, 0.674], (0.674, 2.975], (-0.00534, 0.674], (-3.566, -0.634], ..., (-3.566, -0.634], (-0.634, -0.00534], (-3.566, -0.634], (-3.566, -0.634], (0.674, 2.975]]
Length: 1000
Categories (4, interval[float64]): [(-3.566, -0.634] < (-0.634, -0.00534] < (-0.00534, 0.674] < (0.674, 2.975]]

In [119]:
pd.value_counts(cats)

(0.674, 2.975]        250
(-0.00534, 0.674]     250
(-0.634, -0.00534]    250
(-3.566, -0.634]      250
dtype: int64

In [122]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.267, -0.00534], (-0.00534, 1.27], (-0.00534, 1.27], (-0.00534, 1.27], (-3.566, -1.267], ..., (-3.566, -1.267], (-1.267, -0.00534], (-3.566, -1.267], (-3.566, -1.267], (1.27, 2.975]]
Length: 1000
Categories (4, interval[float64]): [(-3.566, -1.267] < (-1.267, -0.00534] < (-0.00534, 1.27] < (1.27, 2.975]]

In [123]:
data = pd.DataFrame(np.random.randn(1000,4))

In [124]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021293    -0.026717     0.014735    -0.014061
std       1.015968     1.012751     1.012692     0.991036
min      -2.906148    -3.354823    -3.492159    -2.934995
25%      -0.662853    -0.708738    -0.620396    -0.686271
50%       0.081850    -0.021096    -0.008795    -0.017203
75%       0.660001     0.620132     0.688579     0.642665
max       3.013207     3.295766     3.661897     2.817968

In [125]:
col = data[2]

In [126]:
col[np.abs(col)>3]

249   -3.130586
397    3.222036
686   -3.492159
771    3.661897
Name: 2, dtype: float64

In [129]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
249  0.707979 -0.945220 -3.130586 -0.194440
397 -1.055259  0.016885  3.222036  0.065434
404 -0.801341 -3.354823 -0.224699  0.390779
498  0.143201  3.077066 -1.243836 -1.770132
686 -0.728179  0.984211 -3.492159  1.975162
756  0.172331  3.045099 -0.208435 -0.911474
771  1.870999  0.387712  3.661897 -0.006598
883 -0.020284  3.182641  0.244997 -0.590559
951  1.547322  3.104311 -0.166491 -1.263044
960 -0.342120  3.295766 -1.334857  0.206651
993  3.013207 -0.976281 -0.049262 -1.669321

In [130]:
data[(np.abs(data)>3)] = np.sign(data)*3

In [132]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021279    -0.027067     0.014473    -0.014061
std       1.015929     1.009463     1.007847     0.991036
min      -2.906148    -3.000000    -3.000000    -2.934995
25%      -0.662853    -0.708738    -0.620396    -0.686271
50%       0.081850    -0.021096    -0.008795    -0.017203
75%       0.660001     0.620132     0.688579     0.642665
max       3.000000     3.000000     3.000000     2.817968

In [133]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0 -1.0  1.0  1.0
3 -1.0 -1.0 -1.0 -1.0
4 -1.0  1.0  1.0 -1.0

In [134]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [137]:
sampler = np.random.permutation(5)

In [138]:
sampler

array([3, 4, 2, 0, 1])

In [139]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [140]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [141]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3

In [142]:
choices = pd.Series([5,7,-1,6,4])

In [144]:
draws = choices.sample(n=10,replace=True)

In [145]:
draws

3    6
3    6
0    5
4    4
3    6
3    6
1    7
1    7
0    5
2   -1
dtype: int64

In [148]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})

In [149]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [151]:
dummies = pd.get_dummies(df['key'],prefix = 'key')

In [152]:
df_with_dumy = df[['data1']].join(dummies)

In [153]:
df_with_dumy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [155]:
mnames = ['movie_id','title','genres']

In [160]:
movies = pd.read_table('movies.dat',sep='::',header=None,names=mnames)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [162]:
movies[:10]

movie_id  title  genres
0  movie_id     title                            ...    NaN     NaN
1  0 1     Toy Story (1995)                   Ani...    NaN     NaN
2  1 2     Jumanji (1995)                     Adv...    NaN     NaN
3  2 3     Grumpier Old Men (1995)            Com...    NaN     NaN
4  3 4     Waiting to Exhale (1995)           Com...    NaN     NaN
5  4 5     Father of the Bride Part II (1995) Comedy    NaN     NaN
6  5 6     Heat (1995)                        Act...    NaN     NaN
7  6 7     Sabrina (1995)                     Com...    NaN     NaN
8  7 8     Tom and Huck (1995)                Adv...    NaN     NaN
9  8 9     Sudden Death (1995)                Action    NaN     NaN

In [173]:
all_movie_id = []

In [174]:
for x in movies.movie_id:
    all_movie_id.extend(x.split('|'))

In [178]:
movie_id = pd.unique(all_movie_id)

In [179]:
movie_id

array(['movie_id     title                             genres',
       '0 1     Toy Story (1995)                   Animation',
       "Children's", 'Comedy',
       '1 2     Jumanji (1995)                     Adventure', 'Fantasy',
       '2 3     Grumpier Old Men (1995)            Comedy', 'Romance',
       '3 4     Waiting to Exhale (1995)           Comedy', 'Drama',
       '4 5     Father of the Bride Part II (1995) Comedy',
       '5 6     Heat (1995)                        Action', 'Crime',
       'Thriller', '6 7     Sabrina (1995)                     Comedy',
       '7 8     Tom and Huck (1995)                Adventure',
       '8 9     Sudden Death (1995)                Action',
       '9 10    GoldenEye (1995)                   Action', 'Adventure'],
      dtype=object)

In [192]:
zero_matrix = np.zeros((15, len(movie_id)))

In [195]:
dummies = pd.DataFrame(zero_matrix, columns=movie_id)

In [199]:
gen = movies.movie_id

In [209]:
gen = movies.movie_id[2]

In [210]:
gen.split('|')

['1 2     Jumanji (1995)                     Adventure',
 "Children's",
 'Fantasy']

In [211]:
dummies.columns.get_indexer(gen.split('|'))

array([4, 2, 5])

In [212]:
np.random.seed(12345)

In [213]:
values = np.random.randn(10)

In [214]:
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [215]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [216]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           0
1           0           0           1           0           0
2           0           0           0           0           0
3           0           0           0           0           0
4           0           0           0           0           0
5           0           0           0           0           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           1           0
9           0           0           0           0           0

In [217]:
val = 'a,b,guido'

In [218]:
val.split(',')

['a', 'b', 'guido']

In [222]:
pieces = [x.strip() for x in val.split(',')]

In [223]:
pieces

['a', 'b', 'guido']

In [224]:
first,second,third = pieces

In [226]:
first + '::' + second + '::' + third

'a::b::guido'

In [227]:
'::'.join(pieces)

'a::b::guido'

In [228]:
'guido' in val

True

In [229]:
val.index(',')

1

In [230]:
val.find(':')

-1

In [231]:
val.index(':')

ValueError: substring not found

In [232]:
val.count(',')

2

In [233]:
val.replace(',', '::')

'a::b::guido'

In [234]:
val.replace(',', '')

'abguido'

In [238]:
import re

In [242]:
text = "foo bar\t baz \tqux"

In [243]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [244]:
regex = re.compile('\s+')

In [245]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [246]:
regex.findall(text)

[' ', '\t ', ' \t']

In [248]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [249]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [251]:
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [252]:
m = regex.search(text)

In [253]:
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [254]:
text[m.start():m.end()]

'dave@google.com'

In [255]:
print(regex.match(text))

None


In [256]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [257]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [258]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [259]:
m = regex.match('wesm@bright.net')

In [260]:
m.groups()

('wesm', 'bright', 'net')

In [261]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [262]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [263]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [264]:
data = pd.Series(data)

In [265]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [266]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [267]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [268]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [269]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [270]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [271]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [272]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [273]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [274]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object